Mysql
CREATE TABLE registrations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    attachments TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);